## Continuous Integration Jobs definition

stages:
  - test

cache:
  key: "video-streaming-service-client-php"
  paths:
  - .composer-cache/

variables:
  # Configure environment variables for the service
  APP_ENV: local
  APP_KEY: "abcdefghi12345abcdefghi12345"
  APP_URL: "http://docker.klink.asia-images-video-streaming-service/"
  KLINK_REGISTRY_URL: ""
  # Configure environment for the testing
  VIDEO_STREAMING_SERVICE_URL: "http://docker.klink.asia-images-video-streaming-service/"

services:
  - docker.klink.asia/images/video-streaming-service:0.3.1

unit_test:
  stage: test
  image: "edbizarro/gitlab-ci-pipeline-php:7.1"
  script:
    - export COMPOSER_CACHE_DIR=`pwd`/.composer-cache
    - composer install --prefer-dist
    - vendor/bin/phpunit
  tags:
    - docker
